name: Run Go Test on Push

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  go_test:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPAC
      - name: Checks-out the Repository
        uses: actions/checkout@v3

      # Setup Golang
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Prints some relevant information
      - run: echo "repository is ${{ github.repository }}"
      - run: echo "Triggered by a ${{ github.event_name }}"
      - run: echo "Running on ${{ runner.os }}"
      - run: echo "Branch is ${{ github.ref }}"
      - run: echo "Branch is ${{ github.ref }}"
      - run: echo "Go version is $(go version)"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
